# Site settings
title: Prarit Lamba's CV 
description: Prarit Lamba's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /
google_analytics: 

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Prarit Lamba
  title: Master of Science in Information Systems
  address: California,United States
  email: p r a r i t [dot] l a m b a [at] gmail.com
  weibo:
  github: praritlamba
  linkedin: praritlamba
  twitter: 
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: San Diego State University
      location: San Diego , CA
      title: Graduate Research Assistant
      started: 2016
      duration: (2016 - Present)
      description: Reinforcing concepts and guiding students with statistical tools and models.Assisting faculty with research and analysis of statistical modelling,summarizing of reports.Audit and review syllabi for MSIS department using MS Excel and Tableau.Creating and analyzing lecture videos with faculties for Online course development project
    - work2:
      company: Barclays Inc.
      location: New Delhi,India 
      title: Advisor
      started: 2015
      duration: (2015 - 2016)
      description: Analyzed clients existing systems and designed database schema.Developed a functionality that would extract adjustments and charges for Barclaycard Customers from database using SQL queries.Performed audit , review of procedures and documented the procedures.Involved in planning preparation, execution and defect reporting, allocating the issues to the team from Defect tracking/priority tool and generating reports
    - work3:
      company: SparkEighteen Pvt Ltd
      location: New Delhi,India 
      title: Technical Analyst
      started: 2014
      duration: (2014 - 2015)
      description: Initiated project for web development product and data analysis of social media.Tested the product release as needed to support the target release schedule.Analyzed and documented clients issues.
  educationHistory:
    - education1:
      organization: San Diego State University
      location: San Diego, CA
      degree: Master's
      major: Management Of Information Systems 
      started: 2016
      duration: (2016 - 2018)
      description: Courses Enterprise Data Management,Statistical Analysis,Business Data Communication,Marketing,Business Analytics,Financial and Accounting Management,Operations & Supply Chain Management,Seminar in Supply Chain & ERP.      Specializations Tableau, R studio, Statistical Modelling,Data Analysis, Business Analytics, Database Management, Big Data Analysis using Apache Spark
  languages:
    - language1:
      name: Python
      proficiency: 
    - language2:
      name: R
      proficiency: 
    - language3:
      name: PL-SQL
      proficiency: 
    - language4:
      name: MicroStrategy
  programmingSkills:
    - skill1:
      name: Tableau
      percentage: 100%
    - skill2:
      name: R-Studio
      percentage: 90%
    - skill3:
      name: Microsoft Visio
      percentage: 70%
    - skill4:
      name: Apache Spark
      percentage: 70%
    - skill5:
      name: MS Excel
      percentage: 90%
